### ISSUE TITLE
SSO - Transition path

### ISSUE THREAD

**Issue by sherakama** [SU-SWS/stanford_ssp#23]
Create a path for transitioning a website that was using webauth to use this module.

**Comment by jbickar** [comment]
I'd argue against this for D8, especially for MVP. There is no legacy WebAuth baggage for D8; let's not introduce any.

**Comment by pookmish** [comment]
Go back to vacation @jbickar

**Comment by sherakama** [comment]
Yeah, I'd say that this would be for D7 version only. 

Go back to sunshine @jbickar

**Comment by jbickar** [comment]
You stop trying to make bad decisions, I'll go back to vacation.

**Comment by sherakama** [comment]
You are a ray of sunshine.

**Comment by jbickar** [comment]
I *know*; plus, I'm reliable and consistent.

**Comment by sherakama** [comment]
![https://cdn.shopify.com/s/files/1/0535/6917/products/consistencydemotivator.jpeg?v=1414004030](https://cdn.shopify.com/s/files/1/0535/6917/products/consistencydemotivator.jpeg?v=1414004030)

**Comment by jbickar** [comment]
![warning](https://cdn.shopify.com/s/files/1/0535/6917/products/mistakesdemotivator.jpeg?v=1416776264)

**Comment by jbickar** [comment]
This thread warms the cockles of my cold black heart.

It's been solved (for the most part) for D7; "won't fix" for D8.
