### ISSUE TITLE
Faulty HTML on default user login form /user 

### ISSUE THREAD

**Issue by wilsonww** [SU-SWS/stanford_ssp#42]
On stanford_ssp installs with local Drupal user logins still enabled, the /user login form has faulty HTML causing the elements to jump around in the DOM. The input tags for the local user login lands outside of the fieldset that it should be in.

Guessing an extra div tag or missing div tag is the culprit.

Examples: https://coa.cardinalsites.stanford.edu/user https://forms.gse.stanford.edu/user https://openarchive.stanford.edu/user

![screen shot 2018-07-18 at 4 05 54 pm](https://user-images.githubusercontent.com/1642328/42912667-6f36fd60-8aa5-11e8-818c-95743d3a85d8.png)
![screen shot 2018-07-18 at 4 06 13 pm](https://user-images.githubusercontent.com/1642328/42912668-6f520e7a-8aa5-11e8-983f-35d87d5e0a02.png)
![screen shot 2018-07-18 at 4 06 41 pm](https://user-images.githubusercontent.com/1642328/42912669-6f68f9c8-8aa5-11e8-8bd0-4dbc3f776620.png)

**Comment by jbickar** [comment]
I believe this is fixed as of #43
